

# ⚡ Enable Advanced Caching for Faster Builds
[[plugins]]
  package = "@netlify/plugin-gatsby"


# 🛠 Header Optimizations for Performance & Security
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Long-term caching
    X-Frame-Options = "DENY"  # Prevents Clickjacking
    X-XSS-Protection = "1; mode=block"  # Enables XSS protection
    X-Content-Type-Options = "nosniff"  # Prevents MIME type sniffing
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
