export { default as HomepageHero } from "./layout/hero"
export { default as HomepageFeatureList } from "./segments/feature/feature-list"
export { default as HomepageLogoList } from "./ui/logo-list"
export { default as HomepageBenefitList } from "./ui/benefit-list"
// export { default as HomepageStatList } from "./stat-list"
// export { default as HomepageCta } from "./cta"
// export { default as HomepageProductList } from "./product-list"
// export { default as AboutHero } from "./segments/about/about-hero"
// export { default as AboutStatList } from "./segments/about/about-stat-list"
// export { default as AboutLeadership } from "./segments/about/about-leadership"
// export { default as AboutLogoList } from "./segments/about/about-logo-list"
